### PR TITLE
added support for (de)serializing closures/upvalues

### LINKED ISSUE #28: workqueue doesn't support upvalues/closures
I don't have time to fix this. Posting this here in case somebody else wants to give it a shot.

Basically, the problem is illustrated by adding this test to `test_workqueue.lua`:

```lua
...
test {
...
testClosures = function()
      local bias = 0
      local f = function(a, b, c) return bias + math.sqrt((a * a) + (b * b) + (c * c)) end
      q:write(f)
      local f1 = q:read()
      local n = f(1, 2, 3)
      local n1 = f1(1, 2, 3)
      test.mustBeTrue(n == n1, 'Function serialization failed '..n..' ~= '..n1)
   end,
...
```

It will fail:

```lua
test[testClosures] failed - test/test_workqueue.lua:104: attempt to index a nil value (upvalue '_ENV')
stack traceback:
	test/test_workqueue.lua:104: in local 'f1'
	test/test_workqueue.lua:108: in function <test/test_workqueue.lua:102>
	[C]: in function 'xpcall'
	...build-Darwin-x86_64-Lua53/share/lua/5.3/regress/init.lua:43: in function 'regress.run'
	...build-Darwin-x86_64-Lua53/share/lua/5.3/regress/init.lua:182: in local 'test'
	test/test_workqueue.lua:44: in main chunk
	[C]: in function 'dofile'
	...arwin-x86_64-Lua53/lib/luarocks/rocks/trepl/scm-1/bin/th:200: in main chunk
	[C]: in ?	
```

This is because the upvalues (stored in _ENV) don't get serialized.

To solve this, the [`torch.serialize` code](https://github.com/torch/torch7/blob/master/File.lua#L172-L200) would need to be integrated with (i.e. converted to C and such) the [`serialize.c` code](https://github.com/twitter/torch-ipc/blob/master/src/serialize.c#L113-L130). The same is true for deserialization.

In the mean time, functions should be passed to workqueue via something like:

```lua
local upvalues = {1,2,3}
local fn = function(a,b,c) return a + b + c end
queue:write({fn, upvalues})
```

### PR DESCRIPTION
**Pull request by nicholas-leonard**
fixes #28 for Lua 5.2. This won't work with LuaJIT (pretty sure, though untested).

 * [x] ipc.workqueue.writeup() to write upvalues
 * [x] unit test on LuaJIT
 * [x] documentation
  * [x] writeup: how to use and not use upvalues
  * [x] write: multi-write is not documented

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
Just finished discussing this PR with @luketwitter. We think it would be best to have the user accept upvalues/closures by adding arguments to ipc.workqueue, ipc.map, and so on. We also need to add doc explaining some tricky use-cases, i.e.:
```lua
local mylib = require "mylib"

local closure = function()
   ...
   mylib.somefunction()
   ...
end

local q = ipc.workqueue()
q:write(closure, true)
```

In the above, mylib would get serialized. The trick would be to require the package inside the closure:

```lua
local closure = function()
   local mylib = require "mylib"
   ...
   mylib.somefunction()
   ...
end
```

**Comment by soumith** [comment]
imo closures which have upvalues should not be allowed. this makes the interface much more cleaner and usable without magic bad performance issues!

**Comment by nicholas-leonard** [comment]
@soumith Yeah this is why we are making it optional: workqueue.writeup allows for upvalues, workqueue.write doesn't. And all other serializations don't allow them (ipc.map, etc.).

**Comment by soumith** [comment]
ah cool!

**Pull request merged**
